PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS userData;
CREATE TABLE userData(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userName TEXT NOT NULL ,
    password TEXT NOT NULL
    );
CREATE TABLE userCode(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    codeName TEXT NOT NULL,
    createdTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    createdDate DATE DEFAULT CURRENT_DATE,
    userId INTEGER ,
    FOREIGN KEY (userId) REFERENCES userData(id)
);

CREATE TABLE userPlot(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    createdTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    createdDate DATE DEFAULT CURRENT_DATE,
    userId INTEGER,
    FOREIGN KEY (userId) REFERENCES userData(id)
);
